//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Central_SMCS
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DatabaseEntities object using the connection string found in the 'DatabaseEntities' section of the application configuration file.
        /// </summary>
        public DatabaseEntities() : base("name=DatabaseEntities", "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(string connectionString) : base(connectionString, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(EntityConnection connection) : base(connection, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Command> Commands
        {
            get
            {
                if ((_Commands == null))
                {
                    _Commands = base.CreateObjectSet<Command>("Commands");
                }
                return _Commands;
            }
        }
        private ObjectSet<Command> _Commands;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Message> Messages
        {
            get
            {
                if ((_Messages == null))
                {
                    _Messages = base.CreateObjectSet<Message>("Messages");
                }
                return _Messages;
            }
        }
        private ObjectSet<Message> _Messages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Session> Sessions
        {
            get
            {
                if ((_Sessions == null))
                {
                    _Sessions = base.CreateObjectSet<Session>("Sessions");
                }
                return _Sessions;
            }
        }
        private ObjectSet<Session> _Sessions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NewSession> NewSessions
        {
            get
            {
                if ((_NewSessions == null))
                {
                    _NewSessions = base.CreateObjectSet<NewSession>("NewSessions");
                }
                return _NewSessions;
            }
        }
        private ObjectSet<NewSession> _NewSessions;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Commands EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCommands(Command command)
        {
            base.AddObject("Commands", command);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Messages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessages(Message message)
        {
            base.AddObject("Messages", message);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sessions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSessions(Session session)
        {
            base.AddObject("Sessions", session);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NewSessions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNewSessions(NewSession newSession)
        {
            base.AddObject("NewSessions", newSession);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Command")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Command : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Command object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="sessionToken">Initial value of the SessionToken property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        public static Command CreateCommand(global::System.Int32 id, global::System.String sessionToken, global::System.Int32 type, global::System.DateTime dateCreated)
        {
            Command command = new Command();
            command.id = id;
            command.SessionToken = sessionToken;
            command.Type = type;
            command.DateCreated = dateCreated;
            return command;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SessionToken
        {
            get
            {
                return _SessionToken;
            }
            set
            {
                OnSessionTokenChanging(value);
                ReportPropertyChanging("SessionToken");
                _SessionToken = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SessionToken");
                OnSessionTokenChanged();
            }
        }
        private global::System.String _SessionToken;
        partial void OnSessionTokenChanging(global::System.String value);
        partial void OnSessionTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.Int32 _Type;
        partial void OnTypeChanging(global::System.Int32 value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CommandValue
        {
            get
            {
                return _CommandValue;
            }
            set
            {
                OnCommandValueChanging(value);
                ReportPropertyChanging("CommandValue");
                _CommandValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CommandValue");
                OnCommandValueChanged();
            }
        }
        private global::System.String _CommandValue;
        partial void OnCommandValueChanging(global::System.String value);
        partial void OnCommandValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Message")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Message : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Message object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="sessionToken">Initial value of the SessionToken property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="messageValue">Initial value of the MessageValue property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        public static Message CreateMessage(global::System.Int32 id, global::System.String sessionToken, global::System.Int32 type, global::System.String messageValue, global::System.DateTime dateCreated)
        {
            Message message = new Message();
            message.id = id;
            message.SessionToken = sessionToken;
            message.Type = type;
            message.MessageValue = messageValue;
            message.DateCreated = dateCreated;
            return message;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SessionToken
        {
            get
            {
                return _SessionToken;
            }
            set
            {
                OnSessionTokenChanging(value);
                ReportPropertyChanging("SessionToken");
                _SessionToken = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SessionToken");
                OnSessionTokenChanged();
            }
        }
        private global::System.String _SessionToken;
        partial void OnSessionTokenChanging(global::System.String value);
        partial void OnSessionTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.Int32 _Type;
        partial void OnTypeChanging(global::System.Int32 value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessageValue
        {
            get
            {
                return _MessageValue;
            }
            set
            {
                OnMessageValueChanging(value);
                ReportPropertyChanging("MessageValue");
                _MessageValue = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageValue");
                OnMessageValueChanged();
            }
        }
        private global::System.String _MessageValue;
        partial void OnMessageValueChanging(global::System.String value);
        partial void OnMessageValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="NewSession")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NewSession : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NewSession object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="sessionToken">Initial value of the SessionToken property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        public static NewSession CreateNewSession(global::System.Int32 id, global::System.String sessionToken, global::System.String username, global::System.String password, global::System.DateTime dateCreated)
        {
            NewSession newSession = new NewSession();
            newSession.id = id;
            newSession.SessionToken = sessionToken;
            newSession.Username = username;
            newSession.Password = password;
            newSession.DateCreated = dateCreated;
            return newSession;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SessionToken
        {
            get
            {
                return _SessionToken;
            }
            set
            {
                OnSessionTokenChanging(value);
                ReportPropertyChanging("SessionToken");
                _SessionToken = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SessionToken");
                OnSessionTokenChanged();
            }
        }
        private global::System.String _SessionToken;
        partial void OnSessionTokenChanging(global::System.String value);
        partial void OnSessionTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SteamGuardAuth
        {
            get
            {
                return _SteamGuardAuth;
            }
            set
            {
                OnSteamGuardAuthChanging(value);
                ReportPropertyChanging("SteamGuardAuth");
                _SteamGuardAuth = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SteamGuardAuth");
                OnSteamGuardAuthChanged();
            }
        }
        private global::System.String _SteamGuardAuth;
        partial void OnSteamGuardAuthChanging(global::System.String value);
        partial void OnSteamGuardAuthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Session")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Session : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Session object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="sessionToken">Initial value of the SessionToken property.</param>
        /// <param name="iPAddress">Initial value of the IPAddress property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="lastHeartbeat">Initial value of the LastHeartbeat property.</param>
        /// <param name="passKey">Initial value of the PassKey property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static Session CreateSession(global::System.Int32 id, global::System.String sessionToken, global::System.String iPAddress, global::System.DateTime dateCreated, global::System.DateTime lastHeartbeat, global::System.String passKey, global::System.Byte status)
        {
            Session session = new Session();
            session.id = id;
            session.SessionToken = sessionToken;
            session.IPAddress = iPAddress;
            session.DateCreated = dateCreated;
            session.LastHeartbeat = lastHeartbeat;
            session.PassKey = passKey;
            session.Status = status;
            return session;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SessionToken
        {
            get
            {
                return _SessionToken;
            }
            set
            {
                OnSessionTokenChanging(value);
                ReportPropertyChanging("SessionToken");
                _SessionToken = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SessionToken");
                OnSessionTokenChanged();
            }
        }
        private global::System.String _SessionToken;
        partial void OnSessionTokenChanging(global::System.String value);
        partial void OnSessionTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IPAddress
        {
            get
            {
                return _IPAddress;
            }
            set
            {
                OnIPAddressChanging(value);
                ReportPropertyChanging("IPAddress");
                _IPAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IPAddress");
                OnIPAddressChanged();
            }
        }
        private global::System.String _IPAddress;
        partial void OnIPAddressChanging(global::System.String value);
        partial void OnIPAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastHeartbeat
        {
            get
            {
                return _LastHeartbeat;
            }
            set
            {
                OnLastHeartbeatChanging(value);
                ReportPropertyChanging("LastHeartbeat");
                _LastHeartbeat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastHeartbeat");
                OnLastHeartbeatChanged();
            }
        }
        private global::System.DateTime _LastHeartbeat;
        partial void OnLastHeartbeatChanging(global::System.DateTime value);
        partial void OnLastHeartbeatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PassKey
        {
            get
            {
                return _PassKey;
            }
            set
            {
                OnPassKeyChanging(value);
                ReportPropertyChanging("PassKey");
                _PassKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PassKey");
                OnPassKeyChanged();
            }
        }
        private global::System.String _PassKey;
        partial void OnPassKeyChanging(global::System.String value);
        partial void OnPassKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Byte _Status;
        partial void OnStatusChanging(global::System.Byte value);
        partial void OnStatusChanged();

        #endregion
    
    }

    #endregion
    
}
